controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_index:
    path: /
    controller: App\Controller\ArticleController::index

edit_route:
    path: /edit/{id}
    controller: App\Controller\CompteController::edit